title: FloQui Status
buildFuture: true
defaultContentLanguage: nl
languageCode: nl
baseURL: https://status.floqui.nl
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC â€” Jan 2
  down: "#e60000"
  systems:
    - name: Wordpress
      category: Websites
    - name: OctoberCMS
      category: Websites
    - name: Freescout
      category: Websites
    - name: IMAP / POP3 / SMTP
      category: Mail
    - name: Webmail
      category: Mail
    - name: SMTP relay
      category: Mail
      description: Gebruikt om mails te sturen vanuit websites.
    - name: FloQui Cloud
      category: Overig
    - name: DNS servers
      category: Overig
    - name: Budibase
      category: Overig
      description: Dashboard en automatiseringssoftware voor de integratie van
        verschillende systemen via API's
    - name: Appwrite
      category: Overig
      description: API-only backend systeem voor databases, authenticatie, opslag en
        functies voor websites.
    - name: Formulieren
      category: Overig
      description: Software om geavanceerde formulieren mee te bouwen.
    - name: Chatwoot
      category: Overig
      description: Paneel om contact met klanten via mail, live chat en WhatsApp
        business te centraliseren.
    - name: Ghost
      category: Websites
      description: CMS specifiek voor (betaalde) blogs.
    - name: Mautic
      category: Websites
      description: Software voor mass mail marketing
    - name: FloQui Login
      category: Overig
      description: Centraal loginsysteem voor toegang tot verscheidene apps.
    - name: n8n
      category: Overig
      description: Software waarbinnen de automatisering geprogrammeerd worden.
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: https://cdn.floqui.nl/assets/images/branding/logo-inverse.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Websites
      closed: false
    - name: Mail
    - name: Overig
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
